### ISSUE TITLE
CR Servo - 0.5 move does not stop the servo

### ISSUE THREAD

**Issue by samjhill** [tessel/servo-pca9685#17]
I'm still pretty new with this, so bear with me - I have a CR servo, and it rotates at any value between 0 and 1. However, .5 does not seem to stop the servo, as the docs indicate. It continues clockwise at a slow speed. Am I doing something wrong?

```js
servo.move(servo1, 1); //moves clockwise at full speed
setTimeout(function(){servo.move(servo1, 0.5)}, 2000); //moves clockwise at slow speed
```

**Comment by HipsterBrown** [comment]
@samjhill Can you post a link to the hardware description for the CR servo you're using?

**Comment by samjhill** [comment]
https://www.amazon.com/gp/product/B001BHEHIW/ref=oh_aui_search_detailpage?ie=UTF8&psc=1 although mine is black

**Comment by samjhill** [comment]
Setting it to .4 seems to work!

**Comment by dtex** [comment]
@samjhill Most CR servos have a [trim pot like this](https://cdn.sparkfun.com/assets/learn_tutorials/5/2/7/cr-servo-trimmer.jpg) that lets you adjust the zero point. You just need a small screw driver and a gentle touch. They are easy to turn and easy to strip.

**Comment by rwaldron** [comment]
> However, .5 does not seem to stop the servo

Not all servos are exactly the same in this regard; 0.5 is _close_, but may need tweaking none-the-less
